version: "3.8"
services:
  web:
    build: .
    init: true
    ports:
      - 8013:8013
    restart: unless-stopped
    env_file:
      # MUST contain both CYPRESS_USERNAME and CYPRESS_PASSWORD
      - envfile
